# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ph_A6CjNnJ6oiaBOsnHIimHR5fP5qv2x
"""

from pyspark.ml.classification import LogisticRegression, RandomForestClassifier, LinearSVC
from pyspark.ml.evaluation import MulticlassClassificationEvaluator, BinaryClassificationEvaluator
from pyspark.ml.tuning import ParamGridBuilder, TrainValidationSplit



accuracy_eval = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")
f1_eval = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="f1")
precision_eval = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="weightedPrecision")
recall_eval = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="weightedRecall")
auc_eval = BinaryClassificationEvaluator(labelCol="label", rawPredictionCol="rawPrediction", metricName="areaUnderROC")

trained_models = {}
RANDOM_SEED = 42

# Baseline: Logistic Regression

print("Training baseline Logistic Regression...")
lr = LogisticRegression(
    featuresCol="tfidf_features",
    labelCol="label",
    maxIter=30,
    regParam=0.01,
    elasticNetParam=0.0
)
lr_model = lr.fit(train_data)
trained_models["Logistic Regression"] = lr_model
print("✓ Logistic Regression trained")

# Random Forest

print("\nTraining and tuning Random Forest...")
rf = RandomForestClassifier(
    featuresCol="tfidf_features",
    labelCol="label",
    seed=RANDOM_SEED
)

rf_grid = (ParamGridBuilder()
    .addGrid(rf.numTrees, [50, 100])
    .addGrid(rf.maxDepth, [8, 12])
    .build())

rf_tvs = TrainValidationSplit(
    estimator=rf,
    estimatorParamMaps=rf_grid,
    evaluator=f1_eval,
    trainRatio=0.80,
    seed=RANDOM_SEED
)

rf_model = rf_tvs.fit(train_data)
trained_models["Random Forest"] = rf_model
print("✓ Random Forest trained and tuned")

# Linear SVM

print("\nTraining and tuning Linear SVM...")
svm = LinearSVC(
    featuresCol="tfidf_features",
    labelCol="label",
    maxIter=30
)

svm_grid = (ParamGridBuilder()
    .addGrid(svm.regParam, [0.01, 0.1])
    .build())

svm_tvs = TrainValidationSplit(
    estimator=svm,
    estimatorParamMaps=svm_grid,
    evaluator=f1_eval,
    trainRatio=0.80,
    seed=RANDOM_SEED
)

svm_model = svm_tvs.fit(train_data)
trained_models["Linear SVM"] = svm_model
print("✓ Linear SVM trained and tuned")

print("\nAll models trained.")